language: python

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U importlib_metadata; fi

install:
  - pip install tox

script:
  - tox

branches:
  only:
    - master
#    - /^v.*$/

stages:
  - test
#  - name: deploy
#      if: tag IS present
#  - deploy


jobs:
  include:
    - stage: test
      python: 3.12
      env: TOXENV=py312
    - python: 3.11
      env: TOXENV=py311
    - python: 3.10
      env: TOXENV=py310
    - python: 3.9
      env: TOXENV=py39
    - python: 3.8
      env: TOXENV=py38
    - python: 3.7
      env: TOXENV=py37
    - python: 3.6
      env: TOXENV=py36
    - python: 2.7
      env: TOXENV=py27
    - python: pypy3
      env: TOXENV=pypy3
    - python: pypy
      env: TOXENV=pypy